// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzY_z5rnJkjL2nyHU9WZ6LtCcEv2JmDNk',
    appId: '1:865951581625:web:f1a001ccfe6ec6dfbd2268',
    messagingSenderId: '865951581625',
    projectId: 'flutter-auth-874cb',
    authDomain: 'flutter-auth-874cb.firebaseapp.com',
    storageBucket: 'flutter-auth-874cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9_swv4QmR-kKY0GGi2HIttDib8qz76g',
    appId: '1:865951581625:android:9d2f20af9548f91bbd2268',
    messagingSenderId: '865951581625',
    projectId: 'flutter-auth-874cb',
    storageBucket: 'flutter-auth-874cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5qaiEtHNLv5idcQ2cedRjGgke2acvwk',
    appId: '1:865951581625:ios:8756b163d4de26bebd2268',
    messagingSenderId: '865951581625',
    projectId: 'flutter-auth-874cb',
    storageBucket: 'flutter-auth-874cb.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv5qaiEtHNLv5idcQ2cedRjGgke2acvwk',
    appId: '1:865951581625:ios:8756b163d4de26bebd2268',
    messagingSenderId: '865951581625',
    projectId: 'flutter-auth-874cb',
    storageBucket: 'flutter-auth-874cb.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzY_z5rnJkjL2nyHU9WZ6LtCcEv2JmDNk',
    appId: '1:865951581625:web:31c1c92a0abdb729bd2268',
    messagingSenderId: '865951581625',
    projectId: 'flutter-auth-874cb',
    authDomain: 'flutter-auth-874cb.firebaseapp.com',
    storageBucket: 'flutter-auth-874cb.appspot.com',
  );
}
